version: "3.8"
services:
  mongo:
    image: mongo
    volumes:
      -./data:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
