name: Deployment

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deployment:
    environment:
      name: develop
      url: https://get5.cleft.fun
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: brandonrs/get5-web
          tags: |
            type=ref,event=branch
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Docker Compose Remote Deploy
        uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          pull: true
